opdep("scpy","scrdev","home_as_src","scrdev","home_as_src",{"files": [".config/rclone/rclone.conf"]})
opdep("scpy","home","scrdev","home","scrdev",{"files": [".termux/**", ".bash*", ".swi*", ".profile", ".config/rclone/rclone.conf", ".clang-format", "rsyncd.conf"]})
opdep("scpy","etc","scrdev","etc","scrdev",{"files": ["rsyncd.conf", "rsyncd.secrets"]})
opdep("scpy","bin","scrdev","bin","scrdev",{"files": ["termux-*"], "exec": true})
opdep("scpy","sh","scrdev","sh","scrdev",{"files": ["*.sh", "*.env"], "exec": true})
opdep("scpy","py","pyth","py","pyth",{"files": ["*.py"], "exec": true})
opdep("scpy","pl","pro","pl","pro",{"files": ["*.pl"], "exec": true})
opdep("scpy","fdbak","fdb","fdbak","docs",{"files": ["Finance.db"]})
opdep("scpy","backups","fdb","backups","docs",{"files": ["Finance.db"]})
opdep("gitbackup","git","blog","git","blog",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","fdbak","git","fdbak",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","scrdev","git","scrdev",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","bash2","git","bash2",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","pyth","git","pyth",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","pro","git","pro",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","git","js","git","js",{"wt": "/sdcard/projects", "add": true, "commit": true})
opdep("gitbackup","local","git","local","git",{"wt": "/sdcard/projects", "rmt": "local", "push": true})
opdep("gitbackup","bitbucket","git","bitbucket","git",{"wt": "/sdcard/projects", "rmt": "bitbucket", "push": true})
opdep("csbackup","db","blog","db","blog",{"sname": "DropBox"})
opdep("csbackup","db","fdbak","db","fdbak",{"sname": "DropBox"})
opdep("csbackup","db","scrdev","db","scrdev",{"sname": "DropBox"})
opdep("csbackup","db","bash2","db","bash2",{"sname": "DropBox"})
opdep("csbackup","db","pyth","db","pyth",{"sname": "DropBox"})
opdep("csbackup","db","pro","db","pro",{"sname": "DropBox"})
opdep("csbackup","db","js","db","js",{"sname": "DropBox"})
opdep("csbackup","od","blog","od","blog",{"sname": "OneDrive"})
opdep("csbackup","od","fdbak","od","fdbak",{"sname": "OneDrive"})
opdep("csbackup","od","scrdev","od","scrdev",{"sname": "OneDrive"})
opdep("csbackup","od","bash2","od","bash2",{"sname": "OneDrive"})
opdep("csbackup","od","pyth","od","pyth",{"sname": "OneDrive"})
opdep("csbackup","od","pro","od","pro",{"sname": "OneDrive"})
opdep("csbackup","od","js","od","js",{"sname": "OneDrive"})
opdep("csbackup","gd","blog","gd","blog",{"sname": "GoogleDrive"})
opdep("csbackup","gd","fdbak","gd","fdbak",{"sname": "GoogleDrive"})
opdep("csbackup","gd","scrdev","gd","scrdev",{"sname": "GoogleDrive"})
opdep("csbackup","gd","bash2","gd","bash2",{"sname": "GoogleDrive"})
opdep("csbackup","gd","pyth","gd","pyth",{"sname": "GoogleDrive"})
opdep("csbackup","gd","pro","gd","pro",{"sname": "GoogleDrive"})
opdep("csbackup","gd","js","gd","js",{"sname": "GoogleDrive"})
opdep("csbackup","db","docs","db","docs",{"sname": "DropBox"})
opdep("csbackup","od","docs","od","docs",{"sname": "OneDrive"})
opdep("csbackup","gd","docs","gd","docs",{"sname": "GoogleDrive"})
