#!/data/data/com.termux/files/usr/bin/bash


pkg install apt
pkg install autoconf
pkg install automake
pkg install bash
pkg install bc
pkg install binutils
pkg install bison
pkg install build-essential
pkg install busybox
pkg install bzip2
pkg install ca-certificates
pkg install clang
pkg install cmake
pkg install command-not-found
pkg install coreutils
pkg install curl
pkg install dash
pkg install debianutils
pkg install dialog
pkg install diffutils
pkg install dos2unix
pkg install dpkg
pkg install ed
pkg install findutils
pkg install flex
pkg install game-repo
pkg install gawk
pkg install gdbm
pkg install git
pkg install glib
pkg install gperf
pkg install gpgv
pkg install grep
pkg install gzip
pkg install inetutils
pkg install inotify-tools
pkg install jsoncpp
pkg install less
pkg install libandroid-glob
pkg install libandroid-support
pkg install libarchive
pkg install libbz2
pkg install libc++
pkg install libcrypt
pkg install libcurl
pkg install libexpat
pkg install libffi
pkg install libgcrypt
pkg install libgmp
pkg install libgnutls
pkg install libgpg-error
pkg install libiconv
pkg install libidn2
pkg install libllvm
pkg install libltdl
pkg install liblz4
pkg install liblzma
pkg install libmpfr
pkg install libnettle
pkg install libnghttp2
pkg install libsqlite
pkg install libssh2
pkg install libtirpc
pkg install libtool
pkg install libunistring
pkg install libusb
pkg install libuv
pkg install libxml2
pkg install lsof
pkg install m4
pkg install make
pkg install nano
pkg install ncurses-ui-libs
pkg install ncurses
pkg install ndk-sysroot
pkg install net-tools
pkg install openssl
pkg install patch
pkg install pcre2
pkg install pcre
pkg install perl
pkg install pkg-config
pkg install procps
pkg install psmisc
pkg install python
pkg install rclone
pkg install readline
pkg install rhash
pkg install science-repo
pkg install sed
pkg install tar
pkg install termux-am
pkg install termux-api
pkg install termux-exec
pkg install termux-keyring
pkg install termux-licenses
pkg install termux-tools
pkg install unzip
pkg install util-linux
pkg install xxhash
pkg install xz-utils
pkg install zlib
pip install ---------- -------
pip install pip        21.0.1
pip install setuptools 49.2.1
pip install tarjan     0.2.3.2
