#!/data/data/com.termux/files/usr/bin/bash


# pkg install apt
# pkg install bash-completion
# pkg install bash
# pkg install busybox
# pkg install bzip2
# pkg install ca-certificates
# pkg install clang
# pkg install command-not-found
# pkg install coreutils
# pkg install curl
# pkg install dash
# pkg install debianutils
# pkg install dialog
# pkg install diffutils
# pkg install dos2unix
# pkg install dpkg
# pkg install ed
# pkg install findutils
# pkg install gawk
# pkg install gdbm
# pkg install git-crypt
# pkg install git
# pkg install glib
# pkg install gpgv
# pkg install grep
# pkg install gzip
# pkg install inetutils
# pkg install inotify-tools
# pkg install less
# pkg install libandroid-glob
# pkg install libandroid-posix-semaphore
# pkg install libandroid-support
# pkg install libassuan
# pkg install libbz2
# pkg install libc++
# pkg install libcap-ng
# pkg install libcompiler-rt
# pkg install libcrypt
# pkg install libcurl
# pkg install libevent
# pkg install libexpat
# pkg install libffi
# pkg install libgcrypt
# pkg install libgmp
# pkg install libgnutls
# pkg install libgpg-error
# pkg install libiconv
# pkg install libidn2
# pkg install libllvm
# pkg install liblz4
# pkg install liblzma
# pkg install libmd
# pkg install libmpfr
# pkg install libnettle
# pkg install libnghttp2
# pkg install libnpth
# pkg install libsmartcols
# pkg install libsqlite
# pkg install libssh2
# pkg install libunistring
# pkg install libxml2
# pkg install lld
# pkg install llvm
# pkg install make
# pkg install ncurses-ui-libs
# pkg install ncurses
# pkg install ndk-sysroot
# pkg install net-tools
# pkg install openssl-1.1
# pkg install openssl
# pkg install patch
# pkg install pcre2
# pkg install pkg-config
# pkg install procps
# pkg install psmisc
# pkg install python-ensurepip-wheels
# pkg install python-pip
# pkg install python
# pkg install rclone
# pkg install readline
# pkg install resolv-conf
# pkg install ruff
# pkg install sed
# pkg install tar
# pkg install termux-am-socket
# pkg install termux-am
# pkg install termux-exec
# pkg install termux-keyring
# pkg install termux-licenses
# pkg install termux-tools
# pkg install unbound
# pkg install unzip
# pkg install util-linux
# pkg install xxhash
# pkg install xz-utils
# pkg install zlib
# pkg install zstd
# pip install ------------
# pip install asyncinotify
# pip install pip
# pip install tarjan
# pip install xxhash
