#!/data/data/com.termux/files/usr/bin/bash


# pkg install apt
# pkg install attr
# pkg install autoconf
# pkg install automake
# pkg install bash-completion
# pkg install bash
# pkg install bc
# pkg install binutils-bin
# pkg install binutils-libs
# pkg install binutils
# pkg install bison
# pkg install brotli
# pkg install build-essential
# pkg install busybox
# pkg install bzip2
# pkg install c-ares
# pkg install ca-certificates
# pkg install clang
# pkg install cmake
# pkg install command-not-found
# pkg install coreutils
# pkg install curl
# pkg install dart
# pkg install dash
# pkg install debianutils
# pkg install dialog
# pkg install diffutils
# pkg install dos2unix
# pkg install dpkg
# pkg install ed
# pkg install findutils
# pkg install flex
# pkg install fontconfig
# pkg install freetype
# pkg install gawk
# pkg install gdbm
# pkg install giflib
# pkg install git-crypt
# pkg install git-gitk
# pkg install git
# pkg install glib
# pkg install gperf
# pkg install gpgv
# pkg install grep
# pkg install gzip
# pkg install inetutils
# pkg install inotify-tools
# pkg install jsoncpp
# pkg install less
# pkg install libandroid-execinfo
# pkg install libandroid-glob
# pkg install libandroid-posix-semaphore
# pkg install libandroid-shmem
# pkg install libandroid-support
# pkg install libaom
# pkg install libarchive
# pkg install libassuan
# pkg install libbz2
# pkg install libc++
# pkg install libcap-ng
# pkg install libcompiler-rt
# pkg install libcrypt
# pkg install libcurl
# pkg install libdav1d
# pkg install libde265
# pkg install libevent
# pkg install libexpat
# pkg install libffi
# pkg install libgcrypt
# pkg install libgd
# pkg install libgmp
# pkg install libgnutls
# pkg install libgpg-error
# pkg install libgraphite
# pkg install libheif
# pkg install libiconv
# pkg install libicu
# pkg install libidn2
# pkg install libjansson
# pkg install libjpeg-turbo
# pkg install libllvm
# pkg install libltdl
# pkg install liblz4
# pkg install liblzma
# pkg install liblzo
# pkg install libmd
# pkg install libmpfr
# pkg install libnettle
# pkg install libnghttp2
# pkg install libnpth
# pkg install libpixman
# pkg install libpng
# pkg install librav1e
# pkg install libsmartcols
# pkg install libsqlite
# pkg install libssh2
# pkg install libtiff
# pkg install libtirpc
# pkg install libtool
# pkg install libunistring
# pkg install libusb
# pkg install libuv
# pkg install libwebp
# pkg install libx11
# pkg install libx265
# pkg install libxau
# pkg install libxcb
# pkg install libxdmcp
# pkg install libxext
# pkg install libxft
# pkg install libxml2
# pkg install libxrender
# pkg install libxss
# pkg install libyaml
# pkg install lld
# pkg install llvm
# pkg install lsof
# pkg install m4
# pkg install make
# pkg install man
# pkg install nano
# pkg install ncurses-ui-libs
# pkg install ncurses
# pkg install ndk-sysroot
# pkg install net-tools
# pkg install nodejs
# pkg install openssl-1.1
# pkg install openssl
# pkg install patch
# pkg install pcre2
# pkg install pcre
# pkg install perl
# pkg install pkg-config
# pkg install procps
# pkg install psmisc
# pkg install python-ensurepip-wheels
# pkg install python-pip
# pkg install python
# pkg install rclone
# pkg install readline
# pkg install resolv-conf
# pkg install rhash
# pkg install sed
# pkg install tar
# pkg install tcl
# pkg install termux-am-socket
# pkg install termux-am
# pkg install termux-api
# pkg install termux-exec
# pkg install termux-keyring
# pkg install termux-licenses
# pkg install termux-tools
# pkg install tk
# pkg install ttf-dejavu
# pkg install unbound
# pkg install unzip
# pkg install util-linux
# pkg install vim-runtime
# pkg install xxhash
# pkg install xz-utils
# pkg install zlib
# pkg install zstd
# pip install ----------------- -------
# pip install async-to-sync     0.2.3
# pip install black             23.3.0
# pip install click             8.1.3
# pip install isort             5.12.0
# pip install mypy              1.2.0
# pip install mypy-extensions   1.0.0
# pip install packaging         23.1
# pip install pathspec          0.11.1
# pip install pip               23.0.1
# pip install platformdirs      3.2.0
# pip install setuptools        67.6.1
# pip install tarjan            0.2.3.2
# pip install typing_extensions 4.5.0
