#!/data/data/com.termux/files/usr/bin/bash


# pkg uninstall apt
# pkg uninstall attr
# pkg uninstall autoconf
# pkg uninstall automake
# pkg uninstall bash-completion
# pkg uninstall bash
# pkg uninstall bc
# pkg uninstall binutils-bin
# pkg uninstall binutils-libs
# pkg uninstall binutils
# pkg uninstall bison
# pkg uninstall brotli
# pkg uninstall build-essential
# pkg uninstall busybox
# pkg uninstall bzip2
# pkg uninstall c-ares
# pkg uninstall ca-certificates
# pkg uninstall clang
# pkg uninstall cmake
# pkg uninstall command-not-found
# pkg uninstall coreutils
# pkg uninstall curl
# pkg uninstall dart
# pkg uninstall dash
# pkg uninstall debianutils
# pkg uninstall dialog
# pkg uninstall diffutils
# pkg uninstall dos2unix
# pkg uninstall dpkg
# pkg uninstall ed
# pkg uninstall findutils
# pkg uninstall flex
# pkg uninstall fontconfig
# pkg uninstall freetype
# pkg uninstall gawk
# pkg uninstall gdbm
# pkg uninstall giflib
# pkg uninstall git-crypt
# pkg uninstall git-gitk
# pkg uninstall git
# pkg uninstall glib
# pkg uninstall gperf
# pkg uninstall gpgv
# pkg uninstall grep
# pkg uninstall gzip
# pkg uninstall inetutils
# pkg uninstall inotify-tools
# pkg uninstall jsoncpp
# pkg uninstall less
# pkg uninstall libandroid-execinfo
# pkg uninstall libandroid-glob
# pkg uninstall libandroid-posix-semaphore
# pkg uninstall libandroid-shmem
# pkg uninstall libandroid-support
# pkg uninstall libaom
# pkg uninstall libarchive
# pkg uninstall libassuan
# pkg uninstall libbz2
# pkg uninstall libc++
# pkg uninstall libcap-ng
# pkg uninstall libcompiler-rt
# pkg uninstall libcrypt
# pkg uninstall libcurl
# pkg uninstall libdav1d
# pkg uninstall libde265
# pkg uninstall libevent
# pkg uninstall libexpat
# pkg uninstall libffi
# pkg uninstall libgcrypt
# pkg uninstall libgd
# pkg uninstall libgmp
# pkg uninstall libgnutls
# pkg uninstall libgpg-error
# pkg uninstall libgraphite
# pkg uninstall libheif
# pkg uninstall libiconv
# pkg uninstall libicu
# pkg uninstall libidn2
# pkg uninstall libjansson
# pkg uninstall libjpeg-turbo
# pkg uninstall libllvm
# pkg uninstall libltdl
# pkg uninstall liblz4
# pkg uninstall liblzma
# pkg uninstall liblzo
# pkg uninstall libmd
# pkg uninstall libmpfr
# pkg uninstall libnettle
# pkg uninstall libnghttp2
# pkg uninstall libnpth
# pkg uninstall libpixman
# pkg uninstall libpng
# pkg uninstall librav1e
# pkg uninstall libsmartcols
# pkg uninstall libsqlite
# pkg uninstall libssh2
# pkg uninstall libtiff
# pkg uninstall libtirpc
# pkg uninstall libtool
# pkg uninstall libunistring
# pkg uninstall libusb
# pkg uninstall libuv
# pkg uninstall libwebp
# pkg uninstall libx11
# pkg uninstall libx265
# pkg uninstall libxau
# pkg uninstall libxcb
# pkg uninstall libxdmcp
# pkg uninstall libxext
# pkg uninstall libxft
# pkg uninstall libxml2
# pkg uninstall libxrender
# pkg uninstall libxss
# pkg uninstall libyaml
# pkg uninstall lld
# pkg uninstall llvm
# pkg uninstall lsof
# pkg uninstall m4
# pkg uninstall make
# pkg uninstall man
# pkg uninstall nano
# pkg uninstall ncurses-ui-libs
# pkg uninstall ncurses
# pkg uninstall ndk-sysroot
# pkg uninstall net-tools
# pkg uninstall nodejs
# pkg uninstall openssl-1.1
# pkg uninstall openssl
# pkg uninstall patch
# pkg uninstall pcre2
# pkg uninstall pcre
# pkg uninstall perl
# pkg uninstall pkg-config
# pkg uninstall procps
# pkg uninstall psmisc
# pkg uninstall python-ensurepip-wheels
# pkg uninstall python-pip
# pkg uninstall python
# pkg uninstall rclone
# pkg uninstall readline
# pkg uninstall resolv-conf
# pkg uninstall rhash
# pkg uninstall sed
# pkg uninstall tar
# pkg uninstall tcl
# pkg uninstall termux-am-socket
# pkg uninstall termux-am
# pkg uninstall termux-api
# pkg uninstall termux-exec
# pkg uninstall termux-keyring
# pkg uninstall termux-licenses
# pkg uninstall termux-tools
# pkg uninstall tk
# pkg uninstall ttf-dejavu
# pkg uninstall unbound
# pkg uninstall unzip
# pkg uninstall util-linux
# pkg uninstall vim-runtime
# pkg uninstall xxhash
# pkg uninstall xz-utils
# pkg uninstall zlib
# pkg uninstall zstd
# pip uninstall ----------------- -------
 pip uninstall asttokens         2.2.1
# pip uninstall async-to-sync     0.2.3
 pip uninstall black             23.3.0
 pip uninstall cheap-repr        0.5.1
 pip uninstall click             8.1.3
 pip uninstall executing         1.2.0
 pip uninstall isort             5.12.0
 pip uninstall mypy              1.2.0
 pip uninstall mypy-extensions   1.0.0
 pip uninstall packaging         23.1
 pip uninstall pathspec          0.11.1
# pip uninstall pip               23.0.1
 pip uninstall platformdirs      3.2.0
 pip uninstall Pygments          2.15.0
# pip uninstall setuptools        67.6.1
 pip uninstall six               1.16.0
# pip uninstall tarjan            0.2.3.2
 pip uninstall typing_extensions 4.5.0
