#!/data/data/com.termux/files/usr/bin/bash


pkg uninstall apt
pkg uninstall autoconf
pkg uninstall automake
pkg uninstall bash
pkg uninstall bc
pkg uninstall binutils
pkg uninstall bison
pkg uninstall build-essential
pkg uninstall busybox
pkg uninstall bzip2
pkg uninstall ca-certificates
pkg uninstall clang
pkg uninstall cmake
pkg uninstall command-not-found
pkg uninstall coreutils
pkg uninstall curl
pkg uninstall dash
pkg uninstall debianutils
pkg uninstall dialog
pkg uninstall diffutils
pkg uninstall dos2unix
pkg uninstall dpkg
pkg uninstall ed
pkg uninstall findutils
pkg uninstall flex
pkg uninstall game-repo
pkg uninstall gawk
pkg uninstall gdbm
pkg uninstall git
pkg uninstall glib
pkg uninstall gperf
pkg uninstall gpgv
pkg uninstall grep
pkg uninstall gzip
pkg uninstall inetutils
pkg uninstall inotify-tools
pkg uninstall jsoncpp
pkg uninstall less
pkg uninstall libandroid-glob
pkg uninstall libandroid-support
pkg uninstall libarchive
pkg uninstall libbz2
pkg uninstall libc++
pkg uninstall libcrypt
pkg uninstall libcurl
pkg uninstall libexpat
pkg uninstall libffi
pkg uninstall libgcrypt
pkg uninstall libgmp
pkg uninstall libgnutls
pkg uninstall libgpg-error
pkg uninstall libiconv
pkg uninstall libidn2
pkg uninstall libllvm
pkg uninstall libltdl
pkg uninstall liblz4
pkg uninstall liblzma
pkg uninstall libmpfr
pkg uninstall libnettle
pkg uninstall libnghttp2
pkg uninstall libsqlite
pkg uninstall libssh2
pkg uninstall libtirpc
pkg uninstall libtool
pkg uninstall libunistring
pkg uninstall libusb
pkg uninstall libuv
pkg uninstall libxml2
pkg uninstall lsof
pkg uninstall m4
pkg uninstall make
pkg uninstall nano
pkg uninstall ncurses-ui-libs
pkg uninstall ncurses
pkg uninstall ndk-sysroot
pkg uninstall net-tools
pkg uninstall openssl
pkg uninstall patch
pkg uninstall pcre2
pkg uninstall pcre
pkg uninstall perl
pkg uninstall pkg-config
pkg uninstall procps
pkg uninstall psmisc
pkg uninstall python
pkg uninstall rclone
pkg uninstall readline
pkg uninstall rhash
pkg uninstall science-repo
pkg uninstall sed
pkg uninstall tar
pkg uninstall termux-am
pkg uninstall termux-api
pkg uninstall termux-exec
pkg uninstall termux-keyring
pkg uninstall termux-licenses
pkg uninstall termux-tools
pkg uninstall unzip
pkg uninstall util-linux
pkg uninstall xxhash
pkg uninstall xz-utils
pkg uninstall zlib
pip uninstall ---------- -------
pip uninstall pip        21.0.1
pip uninstall setuptools 49.2.1
pip uninstall tarjan     0.2.3.2
